
spring:
  profiles:
    active: prod
logging:
  level:
    top.pippen: debug
    org.hswebframework: debug
    org.hswebframework.expands: error
hsweb:
  cors:
    enable: true
    configs:
      - path: /**
        allowed-headers: "*"
        allowed-methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        allowed-origins: ["*"]
        allow-credentials: true
        max-age: 1800
  dict:
    enum-packages: top.pippen
  file:
    upload:
      static-file-path: ./static/upload
      static-location: http://localhost:8848/upload
  webflux:
    response-wrapper:
      enabled: true #开启响应包装器(将返回值包装为ResponseMessage)
      excludes: # 这下包下的接口不包装
        - org.springdoc
        - org.springframework

  authorize:
    auto-parse: true
    sync: true
server:
  port: 8818

wx:
  miniapp:
    appid: wxe7dc4106112c29a1
    secret: 52bcd608ae506115fc7ba42898a13bcf #pippen博客
    msgDataFormat: JSON

